
name: Python simple test

on:
  push:
      braches: [ "main" ]
  pull_request:
      branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v4
      - name: Prefekt test
        run: python greeting.py